const fs = require("fs");
const { garantirArquivo } = require("./dadosPersistentes.service");
const arquivo = garantirArquivo("cardapio-hamburgueria.json", "data/cardapio-hamburgueria.json", { produtos: [], adicionais: [] });
const categorias = ["hamburgueres", "combos", "complementos", "bebidas"];
const normalizar = valor => String(valor || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();

function ler() { try { const d = JSON.parse(fs.readFileSync(arquivo, "utf8")); return { produtos: Array.isArray(d.produtos) ? d.produtos : [], adicionais: Array.isArray(d.adicionais) ? d.adicionais : [] }; } catch { return { produtos: [], adicionais: [] }; } }
function salvar(dados) { fs.writeFileSync(arquivo, JSON.stringify(dados, null, 2), "utf8"); }
function lista(dados, adicional) { return adicional ? dados.adicionais : dados.produtos; }
function validar(item, adicional) { const nome = String(item?.nome || "").trim(), preco = Number(item?.preco), categoria = adicional ? "complementos" : String(item?.categoria || ""); if (!nome || nome.length > 80) throw Error("Informe o nome do item (até 80 caracteres)."); if (!Number.isFinite(preco) || preco <= 0) throw Error("Informe um preço maior que zero."); if (!categorias.includes(categoria) || (!adicional && categoria === "complementos")) throw Error("Escolha uma categoria válida."); return { nome, preco: Number(preco.toFixed(2)), categoria, descricao: String(item?.descricao || "").trim().slice(0, 500) }; }
function localizar(dados, id, adicional) { const item = lista(dados, adicional).find(valor => valor.id === String(id)); if (!item) throw Error("Item não encontrado."); return item; }
function adicionar(item, adicional = false) { const dados = ler(), novo = validar(item, adicional); if ([...dados.produtos, ...dados.adicionais].some(valor => normalizar(valor.nome) === normalizar(novo.nome))) throw Error("Já existe um item com esse nome."); const salvo = { id: `${adicional ? "complemento" : "produto"}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, ...novo, disponivel: true, imagem: "", promocao: null }; lista(dados, adicional).push(salvo); salvar(dados); return salvo; }
function atualizar(id, alteracoes, adicional = false) { const dados = ler(), item = localizar(dados, id, adicional), proximo = validar({ ...item, ...alteracoes }, adicional); if ([...dados.produtos, ...dados.adicionais].some(valor => valor.id !== item.id && normalizar(valor.nome) === normalizar(proximo.nome))) throw Error("Já existe outro item com esse nome."); Object.assign(item, proximo); salvar(dados); return item; }
function atualizarDisponibilidade(id, disponivel, adicional = false) { const dados = ler(), item = localizar(dados, id, adicional); item.disponivel = Boolean(disponivel); salvar(dados); return item; }
function salvarImagem(id, imagem, adicional = false) { const dados = ler(), item = localizar(dados, id, adicional), valor = String(imagem || ""); if (valor && (!/^data:image\/(png|jpeg|webp);base64,/i.test(valor) || valor.length > 4000000)) throw Error("Envie uma imagem PNG, JPG ou WEBP de até 3 MB."); item.imagem = valor; salvar(dados); return item; }
function salvarPromocao(id, promocao, adicional = false) { const dados = ler(), item = localizar(dados, id, adicional), por = Number(promocao?.precoPromocional); if (!Number.isFinite(por) || por <= 0 || por >= item.preco) throw Error("O preço promocional deve ser maior que zero e menor que o preço atual."); item.promocao = { titulo: String(promocao?.titulo || "Oferta").trim().slice(0, 60), precoPromocional: Number(por.toFixed(2)) }; salvar(dados); return item; }
function removerPromocao(id, adicional = false) { const dados = ler(), item = localizar(dados, id, adicional); item.promocao = null; salvar(dados); return item; }
function remover(id, adicional = false) { const dados = ler(), itens = lista(dados, adicional), i = itens.findIndex(item => item.id === String(id)); if (i < 0) throw Error("Item não encontrado."); const [removido] = itens.splice(i, 1); salvar(dados); return removido; }
function catalogoPublico() { const dados = ler(), publico = item => ({ ...item, precoOriginal: item.preco, preco: item.promocao?.precoPromocional || item.preco }); return { categorias, produtos: dados.produtos.filter(item => item.disponivel !== false).map(publico), adicionais: dados.adicionais.filter(item => item.disponivel !== false).map(publico) }; }
module.exports = { categorias, ler, adicionar, atualizar, atualizarDisponibilidade, salvarImagem, salvarPromocao, removerPromocao, remover, catalogoPublico, normalizar };
